import { CategoryInfo, SavingsGoal, Transaction, CategoryBudgetMap } from '../types/finance';

export const CATEGORIES: Record<string, CategoryInfo> = {
  // Pengeluaran Spesifik Sesuai Permintaan Pengguna:
  makan: {
    id: 'makan',
    label: 'Biaya Makan',
    shortLabel: 'Makan',
    type: 'expense',
    color: '#f97316', // Vibrant Orange
    budgetGroup: 'needs',
  },
  transportasi: {
    id: 'transportasi',
    label: 'Transportasi',
    shortLabel: 'Transport',
    type: 'expense',
    color: '#38bdf8', // Neon Sky-400
    budgetGroup: 'needs',
  },
  jajan: {
    id: 'jajan',
    label: 'Jajan & Kopi',
    shortLabel: 'Jajan',
    type: 'expense',
    color: '#fb7185', // Rose/Pink-400
    budgetGroup: 'wants',
  },
  keperluan: {
    id: 'keperluan',
    label: 'Keperluan Rumah/Pribadi',
    shortLabel: 'Keperluan',
    type: 'expense',
    color: '#c084fc', // Purple-400
    budgetGroup: 'needs',
  },
  game: {
    id: 'game',
    label: 'Game & Top-up',
    shortLabel: 'Game',
    type: 'expense',
    color: '#34d399', // Emerald-400
    budgetGroup: 'wants',
  },
  lainnya: {
    id: 'lainnya',
    label: 'Pengeluaran Lainnya',
    shortLabel: 'Lainnya',
    type: 'expense',
    color: '#94a3b8', // Slate-400
    budgetGroup: 'wants',
  },

  // Pemasukan (Income)
  gaji: {
    id: 'gaji',
    label: 'Gaji Pokok / Upah',
    shortLabel: 'Gaji',
    type: 'income',
    color: '#10b981',
  },
  sampingan: {
    id: 'sampingan',
    label: 'Pekerjaan Sampingan',
    shortLabel: 'Sampingan',
    type: 'income',
    color: '#14b8a6',
  },
  uang_saku: {
    id: 'uang_saku',
    label: 'Uang Saku / Kiriman',
    shortLabel: 'Uang Saku',
    type: 'income',
    color: '#06b6d4',
  },
  pemasukan_lain: {
    id: 'pemasukan_lain',
    label: 'Pemasukan Lainnya',
    shortLabel: 'Lain-lain',
    type: 'income',
    color: '#2dd4bf',
  },

  // Tabungan (Savings)
  tabungan_utama: {
    id: 'tabungan_utama',
    label: 'Tabungan Rekening',
    shortLabel: 'Tabungan',
    type: 'savings',
    color: '#60a5fa',
    budgetGroup: 'savings',
  },
  dana_darurat: {
    id: 'dana_darurat',
    label: 'Setoran Dana Darurat',
    shortLabel: 'Dana Darurat',
    type: 'savings',
    color: '#3b82f6',
    budgetGroup: 'savings',
  },
  investasi: {
    id: 'investasi',
    label: 'Investasi / Reksadana',
    shortLabel: 'Investasi',
    type: 'savings',
    color: '#818cf8',
    budgetGroup: 'savings',
  },
  tabungan_game_gadget: {
    id: 'tabungan_game_gadget',
    label: 'Tabungan Gadget / PC Game',
    shortLabel: 'Tabungan PC',
    type: 'savings',
    color: '#38bdf8',
    budgetGroup: 'savings',
  },
};

export const DEFAULT_CATEGORY_BUDGETS: CategoryBudgetMap = {
  makan: 1500000,
  transportasi: 500000,
  jajan: 350000,
  keperluan: 800000,
  game: 250000,
  lainnya: 200000,
};

export const PAYMENT_METHODS: { id: string; label: string }[] = [
  { id: 'qris', label: 'QRIS / E-Wallet (GoPay/Shopee)' },
  { id: 'bank_transfer', label: 'Transfer Bank (BCA/Mandiri/BRI)' },
  { id: 'cash', label: 'Uang Tunai (Cash)' },
  { id: 'kartu', label: 'Kartu Debit / Kredit' },
];

export const INITIAL_SAVINGS_GOALS: SavingsGoal[] = [
  {
    id: 'goal-1',
    title: 'Dana Darurat 6 Bulan',
    targetAmount: 18000000,
    currentAmount: 11200000,
    monthlyTarget: 1000000,
    deadlineDate: '2027-06-30',
    category: 'emergency',
    notes: 'Cadangan darurat di rekening likuid terpisah',
    createdAt: Date.now() - 60 * 86400000,
  },
  {
    id: 'goal-2',
    title: 'Beli PC Gaming & Konsol Baru',
    targetAmount: 15000000,
    currentAmount: 7500000,
    monthlyTarget: 1250000,
    deadlineDate: '2027-02-28',
    category: 'game',
    notes: 'Upgrade setup PC untuk gaming & kerja',
    createdAt: Date.now() - 90 * 86400000,
  },
  {
    id: 'goal-3',
    title: 'Tabungan Masa Depan / Rumah',
    targetAmount: 50000000,
    currentAmount: 16500000,
    monthlyTarget: 1500000,
    deadlineDate: '2028-12-31',
    category: 'house',
    notes: 'Disimpan di instrumen investasi obligasi & reksadana',
    createdAt: Date.now() - 120 * 86400000,
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  // Pemasukan
  {
    id: 'tx-inc-1',
    type: 'income',
    amount: 7500000,
    category: 'gaji',
    description: 'Gaji Bulanan',
    date: '2026-09-01',
    paymentMethod: 'bank_transfer',
    createdAt: Date.now() - 28 * 86400000,
  },
  {
    id: 'tx-inc-2',
    type: 'income',
    amount: 1500000,
    category: 'sampingan',
    description: 'Jasa Freelance / Desain Grafis Klien',
    date: '2026-09-12',
    paymentMethod: 'bank_transfer',
    createdAt: Date.now() - 17 * 86400000,
  },

  // 1. Biaya Makan
  {
    id: 'tx-makan-1',
    type: 'expense',
    amount: 350000,
    category: 'makan',
    description: 'Belanja Bahan Makanan & Lauk Mingguan',
    date: '2026-09-03',
    paymentMethod: 'qris',
    createdAt: Date.now() - 26 * 86400000,
  },
  {
    id: 'tx-makan-2',
    type: 'expense',
    amount: 125000,
    category: 'makan',
    description: 'Makan Siang Bersama Teman Kantor',
    date: '2026-09-07',
    paymentMethod: 'qris',
    createdAt: Date.now() - 22 * 86400000,
  },
  {
    id: 'tx-makan-3',
    type: 'expense',
    amount: 420000,
    category: 'makan',
    description: 'Beli Beras, Telur, Minyak & Daging',
    date: '2026-09-15',
    paymentMethod: 'cash',
    createdAt: Date.now() - 14 * 86400000,
  },
  {
    id: 'tx-makan-4',
    type: 'expense',
    amount: 85000,
    category: 'makan',
    description: 'Makan Malam Nasi Padang & Es Teh',
    date: '2026-09-21',
    paymentMethod: 'cash',
    createdAt: Date.now() - 8 * 86400000,
  },

  // 2. Biaya Transportasi
  {
    id: 'tx-trans-1',
    type: 'expense',
    amount: 100000,
    category: 'transportasi',
    description: 'Isi Bensin Pertamax Motor',
    date: '2026-09-04',
    paymentMethod: 'cash',
    createdAt: Date.now() - 25 * 86400000,
  },
  {
    id: 'tx-trans-2',
    type: 'expense',
    amount: 75000,
    category: 'transportasi',
    description: 'Top-up Saldo Kartu KRL / MRT',
    date: '2026-09-08',
    paymentMethod: 'qris',
    createdAt: Date.now() - 21 * 86400000,
  },
  {
    id: 'tx-trans-3',
    type: 'expense',
    amount: 110000,
    category: 'transportasi',
    description: 'Ongkos Ojek Online saat Hujan',
    date: '2026-09-17',
    paymentMethod: 'qris',
    createdAt: Date.now() - 12 * 86400000,
  },
  {
    id: 'tx-trans-4',
    type: 'expense',
    amount: 85000,
    category: 'transportasi',
    description: 'Ganti Oli & Servis Rutin Motor',
    date: '2026-09-24',
    paymentMethod: 'bank_transfer',
    createdAt: Date.now() - 5 * 86400000,
  },

  // 3. Biaya Jajan
  {
    id: 'tx-jajan-1',
    type: 'expense',
    amount: 45000,
    category: 'jajan',
    description: 'Es Kopi Susu Gula Aren & Roti Bakar',
    date: '2026-09-05',
    paymentMethod: 'qris',
    createdAt: Date.now() - 24 * 86400000,
  },
  {
    id: 'tx-jajan-2',
    type: 'expense',
    amount: 38000,
    category: 'jajan',
    description: 'Minuman Boba Sore',
    date: '2026-09-10',
    paymentMethod: 'qris',
    createdAt: Date.now() - 19 * 86400000,
  },
  {
    id: 'tx-jajan-3',
    type: 'expense',
    amount: 65000,
    category: 'jajan',
    description: 'Cemilan Gorengan & Martabak Manis',
    date: '2026-09-18',
    paymentMethod: 'cash',
    createdAt: Date.now() - 11 * 86400000,
  },
  {
    id: 'tx-jajan-4',
    type: 'expense',
    amount: 52000,
    category: 'jajan',
    description: 'Nongkrong Kafe & Snack Kentang',
    date: '2026-09-25',
    paymentMethod: 'qris',
    createdAt: Date.now() - 4 * 86400000,
  },

  // 4. Biaya Keperluan
  {
    id: 'tx-kep-1',
    type: 'expense',
    amount: 220000,
    category: 'keperluan',
    description: 'Sabun Mandi, Shampoo, Pasta Gigi & Deterjen',
    date: '2026-09-02',
    paymentMethod: 'kartu',
    createdAt: Date.now() - 27 * 86400000,
  },
  {
    id: 'tx-kep-2',
    type: 'expense',
    amount: 150000,
    category: 'keperluan',
    description: 'Paket Data Internet 50GB & Pulsa HP',
    date: '2026-09-06',
    paymentMethod: 'qris',
    createdAt: Date.now() - 23 * 86400000,
  },
  {
    id: 'tx-kep-3',
    type: 'expense',
    amount: 180000,
    category: 'keperluan',
    description: 'Galon Air Mineral, Gas Elpiji & Tisu',
    date: '2026-09-14',
    paymentMethod: 'cash',
    createdAt: Date.now() - 15 * 86400000,
  },
  {
    id: 'tx-kep-4',
    type: 'expense',
    amount: 90000,
    category: 'keperluan',
    description: 'Obat Vitamin C, Flu & Minyak Kayu Putih',
    date: '2026-09-22',
    paymentMethod: 'qris',
    createdAt: Date.now() - 7 * 86400000,
  },

  // 5. Biaya Game
  {
    id: 'tx-game-1',
    type: 'expense',
    amount: 85000,
    category: 'game',
    description: 'Top-up Weekly Diamond Pass Mobile Legends',
    date: '2026-09-09',
    paymentMethod: 'qris',
    createdAt: Date.now() - 20 * 86400000,
  },
  {
    id: 'tx-game-2',
    type: 'expense',
    amount: 120000,
    category: 'game',
    description: 'Beli Game Indie Diskon Steam Sale',
    date: '2026-09-16',
    paymentMethod: 'kartu',
    createdAt: Date.now() - 13 * 86400000,
  },

  // Tabungan & Setoran
  {
    id: 'tx-tab-1',
    type: 'savings',
    amount: 1000000,
    category: 'dana_darurat',
    description: 'Setoran Rutin Dana Darurat ke Rekening Tabungan',
    date: '2026-09-03',
    paymentMethod: 'bank_transfer',
    savingsGoalId: 'goal-1',
    createdAt: Date.now() - 26 * 86400000,
  },
  {
    id: 'tx-tab-2',
    type: 'savings',
    amount: 1250000,
    category: 'tabungan_game_gadget',
    description: 'Tabungan Khusus Upgrade Setup PC Gaming',
    date: '2026-09-05',
    paymentMethod: 'bank_transfer',
    savingsGoalId: 'goal-2',
    createdAt: Date.now() - 24 * 86400000,
  },
  {
    id: 'tx-tab-3',
    type: 'savings',
    amount: 1500000,
    category: 'investasi',
    description: 'Setoran Rutin Tabungan Investasi Masa Depan',
    date: '2026-09-08',
    paymentMethod: 'bank_transfer',
    savingsGoalId: 'goal-3',
    createdAt: Date.now() - 21 * 86400000,
  }
];
